apiVersion: v2
name: scenario-1
description: DevopsBEERer Scenario 1 - Basic SPA with OIDC Authentication
type: application
version: 0.2.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/DevOpsBeerer/playground-scenarios-charts/beer-icon.png

keywords:
  - oidc
  - oauth2
  - authentication
  - devops
  - tutorial
  - keycloak
  - spa

maintainers:
  - name: DevopsBEERer Team

home: https://github.com/DevOpsBeerer/playground-scenarios-charts
sources:
  - https://github.com/DevOpsBeerer/playground-scenarios-charts

annotations:
  category: Authentication
  licenses: MIT
