{{- if .Values.frontoffice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backoffice.name }}-config
  labels:
    {{- include "scenario-2.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontoffice
data:
  KEYCLOAK_ISSUER: "{{ include "scenario-2.ssoPublicUrl" . }}/realms/{{ .Values.sso.realm }}",
{{- end }}