{{- if .Values.backoffice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backoffice.name }}
  labels:
    {{- include "scenario-2.labels" . | nindent 4 }}
    app.kubernetes.io/component: backoffice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scenario-2.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backoffice
  template:
    metadata:
      labels:
        {{- include "scenario-2.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backoffice
        app: {{ .Values.backoffice.name }}
    spec:
      securityContext:
        {{- include "scenario-2.podSecurityContext" . | nindent 8 }}
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      {{- include "scenario-2.dnsConfig" . | nindent 6 }}
      containers:
        - name: backoffice
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.backoffice.image.repository }}:{{ .Values.backoffice.image.tag }}"
          imagePullPolicy: {{ .Values.backoffice.image.pullPolicy }}
          securityContext:
            {{- include "scenario-2.containerSecurityContext" . | nindent 12 }}
            runAsUser: 101
            runAsGroup: 101
          ports:
            - containerPort: {{ .Values.backoffice.service.port }}
              protocol: TCP
              name: http
          resources:
            {{- toYaml .Values.backoffice.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backoffice.healthCheck.liveness.path }}
              port: {{ .Values.backoffice.service.port }}
            initialDelaySeconds: {{ .Values.backoffice.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backoffice.healthCheck.liveness.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.backoffice.healthCheck.readiness.path }}
              port: {{ .Values.backoffice.service.port }}
            initialDelaySeconds: {{ .Values.backoffice.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backoffice.healthCheck.readiness.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
{{- end }}