{{- if and .Values.frontoffice.enabled .Values.frontoffice.ingress.enabled }}
{{- $config := .Values.frontoffice.ingress }}
{{- $_ := set $config "servicePort" .Values.frontoffice.service.port }}
{{- include "scenario-2.ingress" (dict "component" "frontoffice" "config" $config "root" .) }}
{{- end }}