{{- if and .Values.backoffice.enabled .Values.backoffice.ingress.enabled }}
{{- $config := .Values.backoffice.ingress }}
{{- $_ := set $config "servicePort" .Values.backoffice.service.port }}
{{- include "scenario-2.ingress" (dict "component" "backoffice" "config" $config "root" .) }}
{{- end }}