{{- if .Values.frontoffice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontoffice.name }}-config
  labels:
    {{- include "scenario-1.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontoffice
data:
  config.json: >
    {
      "devopsbeerUrl": "{{ include "scenario-1.apiUrl" . }}",
      "version": "{{ .Values.frontoffice.config.version }}",
      "environment": "{{ .Values.frontoffice.config.environment }}",
      "organizationName": "{{ .Values.frontoffice.config.organizationName }}"
    }

  auth.json: >
    {
        "authority": "{{ include "scenario-1.ssoPublicUrl" . }}/realms/{{ .Values.sso.realm }}",
        "redirectUrl": "https://{{ .Values.frontoffice.ingress.host }}/callback",
        "postLogoutRedirectUri": "https://{{ .Values.frontoffice.ingress.host }}",
        "clientId": "{{ .Values.frontoffice.config.clientId }}",
        "secureRoutes": [
            "{{ include "scenario-1.apiUrl" . }}/"
        ],
        "scopes": {{ .Values.frontoffice.config.scopes | toJson }}
    }
{{- end }}