apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  KEYCLOAK_URL: http://sso-keycloak-headless.sso.svc.cluster.local:8080
  KEYCLOAK_AUDIENCE: scenario-1-api
  KEYCLOAK_REALM: devopsbeerer
  NODE_ENV: development