apiVersion: v1
kind: Service
metadata:
  labels:
    app: scenario-1-api
  name: scenario-1-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    app: scenario-1-api